# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Despliegue Frontend Estatico IDEC

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@v4

      - name: Iniciar sesion en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5739535D338742DBB60DEF0CF18A1DDF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2C63594C69F244EB8AAA38AF0BA7885 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DAD47BE2298B49E787614A2E96076562 }}

      - name: Desplegar archivos HTML a Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sistema-idec-frontend'
          slot-name: 'Production'
          package: .
          
